import java.util.Arrays;

public class Day2 {
    public static void main(String... args) {
        a();
        b();
    }

    private static void a() {
        long sum = Arrays.stream(input.split("\n"))
                         .map(RoundA::parse)
                         .mapToLong(RoundA::score)
                         .sum();

        System.out.println(sum);
    }

    private static void b() {
        long sum = Arrays.stream(input.split("\n"))
                         .map(RoundB::parse)
                         .mapToLong(RoundB::score)
                         .sum();

        System.out.println(sum);
    }

    record RoundA(Shape me, Shape opponent) {
        int score() {
            return outcome().score + me.value;
        }

        Outcome outcome() {
            if (me.beats(opponent)) {
                return Outcome.WIN;
            } else if (me.draws(opponent)) {
                return Outcome.DRAW;
            } else {
                return Outcome.LOSE;
            }
        }

        static RoundA parse(String line) {
            String[] cols = line.split(" ");
            return new RoundA(Shape.parse(cols[1]), Shape.parse(cols[0]));
        }
    }

    enum Outcome {
        WIN(6),
        DRAW(3),
        LOSE(0);

        private final int score;

        Outcome(int score) {
            this.score = score;
        }

        public static Outcome parse(String name) {
            return name.equals("X") ? LOSE : (name.equals("Y") ? DRAW : WIN);
        }
    }

    record RoundB(Shape opponent, Outcome outcome) {
        int score() {
            return me().value + outcome.score;
        }

        Shape me() {
            for (Shape s : Shape.values()) {
                switch (outcome) {
                case WIN:
                    if (s.beats(opponent)) {
                        return s;
                    }
                    break;
                case DRAW:
                    if (s.draws(opponent)) {
                        return s;
                    }
                    break;
                case LOSE:
                    if (s.loses(opponent)) {
                        return s;
                    }
                    break;
                }
            }

            throw new IllegalStateException();
        }

        static RoundB parse(String line) {
            String[] cols = line.split(" ");
            return new RoundB(Shape.parse(cols[0]), Outcome.parse(cols[1]));
        }
    }

    enum Shape {
        ROCK("X", "A", 1),
        PAPER("Y", "B", 2),
        SCISSORS("Z", "C", 3);

        private final String opponentCode;
        private final String myCode;
        final int value;

        Shape(String opponentCode, String myCode, int value) {
            this.opponentCode = opponentCode;
            this.myCode = myCode;
            this.value = value;
        }

        boolean beats(Shape that) {
            return switch (this) {
                case ROCK -> (that == SCISSORS);
                case PAPER -> (that == ROCK);
                case SCISSORS -> (that == PAPER);
            };
        }

        boolean draws(Shape that) {
            return this == that;
        }

        boolean loses(Shape that) {
            return !beats(that) && !draws(that);
        }

        static Shape parse(String code) {
            for (Shape s : values()) {
                if (s.opponentCode.equals(code) || s.myCode.equals(code)) {
                    return s;
                }
            }

            throw new IllegalArgumentException();
        }
    }

    private static final String input = """
            C Y
            B Z
            B Z
            C Y
            B Y
            C Z
            C Z
            C Y
            B Z
            C Z
            C X
            C Y
            C Z
            C Y
            C Y
            B Z
            A Y
            C Z
            C Z
            C Z
            B X
            B Z
            C Y
            A X
            C X
            C Z
            C Y
            C Z
            C Z
            C Z
            C Y
            C Y
            A X
            C X
            C Z
            B Z
            B Z
            B Z
            B Z
            C Z
            C Y
            C Z
            B Z
            A Y
            A X
            C Z
            C Y
            C Z
            C Y
            C Z
            A X
            C Z
            C Z
            C Z
            C Z
            C Y
            C Y
            C Z
            C Z
            C Z
            C Z
            B X
            C Y
            B Y
            B X
            A X
            C Y
            C Z
            C Z
            C Y
            C Z
            C Z
            A Y
            C Y
            C Z
            C Y
            B Z
            C Z
            C Y
            B Z
            B Z
            C Z
            C Y
            C Y
            C Z
            C Z
            C Y
            C Z
            C Y
            C Y
            C Y
            C Y
            B X
            C Z
            C Z
            C X
            C X
            C Z
            B Z
            A Y
            C Y
            A Y
            C Y
            C Z
            C Y
            C Z
            C Y
            B Z
            C Z
            C Z
            C Y
            A Y
            C Z
            B Z
            C Z
            C Z
            C X
            C Z
            C Z
            C Z
            C Z
            C Z
            C Z
            B Z
            C Z
            C Y
            B Z
            C Y
            C X
            A X
            C Z
            A Y
            C Y
            C Z
            B Z
            C Z
            B X
            C Z
            C Y
            C Z
            B Z
            C Z
            C Z
            C Y
            C Y
            C Y
            B Z
            C Y
            C Y
            B X
            C Z
            B Z
            B Z
            C Z
            C Z
            C Z
            C Z
            C Z
            A Y
            C Y
            C Z
            C Y
            B Z
            B Z
            C Y
            C Z
            B Z
            C Y
            C Y
            C Z
            B Z
            C Y
            C Z
            C Y
            B Z
            C Z
            A X
            C Z
            C Y
            C Z
            B Z
            C Z
            C Y
            C Y
            C Y
            C Y
            C Y
            C Z
            C Z
            A Y
            C Z
            C Z
            C Z
            C Y
            B Z
            C Z
            B Z
            C Z
            C X
            C X
            B Z
            C Y
            C X
            C Y
            B Z
            C Y
            C X
            C Z
            C Z
            C Y
            C Z
            C Z
            B Z
            A X
            C Y
            C Z
            C Z
            C Z
            C Y
            C Y
            C Z
            C Z
            C Y
            C Z
            A Y
            C Z
            B Z
            C Z
            A Z
            C Z
            C X
            B Z
            C Y
            C X
            C Z
            C X
            C Y
            A Y
            C Y
            C Y
            C Z
            C Z
            C Y
            B Z
            A X
            C Z
            C X
            C Y
            B Z
            C X
            C Z
            C Y
            C Z
            C Y
            A Y
            B Z
            C Z
            C Y
            C Y
            C Z
            B Y
            C Y
            B X
            C Y
            C Y
            C Z
            C Z
            C Z
            C Y
            C Y
            C Y
            B X
            C Z
            C Z
            C Z
            B X
            A Y
            C Z
            C Z
            A Y
            B Z
            C Z
            A X
            C Z
            C Z
            C Z
            C X
            C Y
            C Y
            C Z
            C Z
            C Z
            C Z
            C Z
            C Z
            C Y
            B Y
            C Z
            C Z
            C Y
            C Z
            C Z
            C Y
            C Z
            A Y
            C Y
            C Z
            B Y
            A X
            B Z
            C Z
            C Z
            C Z
            A Z
            C Z
            B Z
            B Z
            C Y
            B X
            C Z
            C Y
            C Z
            C Y
            A Y
            C Z
            C Z
            C Z
            B Z
            B Z
            C Y
            C Z
            C Y
            C Z
            C X
            C Z
            C Y
            C Y
            C Y
            C X
            B Y
            C Y
            B Z
            C Z
            C Z
            C Y
            C Y
            C Z
            C Z
            C Y
            C Y
            C Z
            C Z
            C Z
            C Y
            C Y
            C Z
            C Z
            C Y
            B Z
            C Z
            C X
            A Y
            B Z
            C Z
            C Z
            B Z
            C Z
            B Z
            C Y
            C X
            C Z
            C Z
            A Y
            C X
            C Y
            A X
            C Z
            C Z
            C Z
            B Z
            C Z
            C Y
            B Z
            B Z
            C Z
            C Z
            A Y
            C X
            C Z
            B Z
            C Z
            C Z
            C Z
            B Z
            C Z
            C Z
            B Z
            C Z
            C Y
            C X
            C Z
            C Z
            A Y
            C Z
            C Z
            C Z
            A Z
            B X
            C X
            C Y
            C Z
            C Y
            C Y
            C X
            C Z
            B Z
            C Z
            A Y
            C Y
            C Z
            A X
            B Z
            B Z
            A Y
            C Z
            C Z
            C X
            C Z
            C Y
            C Y
            C Z
            C Y
            B Y
            C Y
            C Z
            C Y
            C Z
            C Z
            C X
            C Z
            C Y
            C Z
            C Y
            A X
            C Z
            B Z
            B Z
            C Y
            C Y
            C Y
            C Y
            C Z
            C Y
            A X
            C Z
            B Z
            C Y
            C Y
            C Z
            C Z
            C Y
            C Z
            C Z
            C Z
            C Z
            C Z
            B Z
            C Z
            C Y
            C X
            C Z
            C Z
            B Z
            C Z
            C Z
            C Z
            B Z
            C X
            B Z
            A Z
            C Z
            C Y
            C Y
            C Y
            B Z
            C X
            A Y
            C X
            C Y
            B Z
            C Y
            B Y
            A X
            B Z
            C Z
            B Z
            C Y
            B Z
            B X
            C Y
            C Z
            C Y
            C Y
            C Z
            B Z
            C Z
            C Z
            C Y
            C Z
            B Z
            B Y
            C Z
            C Y
            A Y
            C Z
            C Z
            A X
            C Z
            B Z
            C Z
            A Z
            C Z
            C X
            C Z
            C Z
            C Z
            C Z
            C Z
            C Z
            B Z
            C Y
            B Z
            B X
            C Y
            C Z
            B Z
            C Z
            C Y
            C Y
            C Y
            B Z
            B Y
            C Y
            C Y
            C Z
            C Z
            C Z
            B Y
            C Y
            C Y
            C Y
            C Z
            A X
            C Y
            B Z
            C Z
            A X
            A X
            C Z
            C Y
            B X
            C X
            B Y
            C Y
            C X
            A Y
            C Z
            C X
            C Z
            B X
            A Y
            C Y
            C X
            B Z
            C Y
            C Z
            C Z
            C X
            C Y
            C Z
            C Z
            C Z
            C X
            A X
            C Y
            A Y
            C Z
            C Z
            C Z
            C Y
            C Y
            C Z
            C Z
            C X
            C Z
            C Y
            B Z
            B Z
            C X
            C Z
            B Y
            C Z
            B Z
            C Z
            C Z
            B X
            C Y
            A Y
            C Z
            C Z
            A Y
            C Z
            C Y
            C Y
            C Z
            C Z
            C Z
            C Z
            B Y
            C Y
            C Y
            C X
            C Z
            C Z
            C Z
            B Y
            A Y
            A X
            A X
            C Z
            C Z
            C Y
            A Y
            C Z
            C Z
            B Z
            C Y
            C Z
            C Z
            A X
            C Z
            C Z
            C Z
            C X
            C Y
            C Z
            C Y
            A X
            C Y
            C Z
            A Y
            C Z
            C Z
            B Z
            B Z
            C Z
            A Y
            A X
            C Y
            C Z
            C Y
            A Z
            C Y
            A Y
            B Z
            C Z
            C Z
            C X
            A Y
            C Y
            C Y
            C Y
            B Z
            B X
            A X
            C Y
            B Z
            C X
            C Z
            C Z
            C Y
            C Y
            C Y
            C Z
            C Z
            A Y
            C Z
            C Z
            C Z
            C Z
            C Y
            B Z
            C Z
            C Z
            B Z
            C Y
            A Y
            C Z
            C X
            B Z
            C Z
            A X
            C Y
            A Y
            C Z
            C Y
            A X
            A X
            B X
            C Y
            C Z
            C Z
            C X
            B X
            C Z
            C Z
            A X
            C Z
            C Z
            B Z
            C Z
            C Y
            C X
            C Z
            A X
            C Z
            C Y
            C Z
            C Y
            B Z
            C Y
            A X
            C Z
            A X
            C X
            C Z
            B Z
            C Y
            C Z
            B Z
            B X
            C Y
            C Z
            C Y
            B Z
            C Y
            C Z
            B Z
            B Z
            C Y
            B Y
            C Z
            C Y
            B Z
            B X
            B Z
            A Y
            C Z
            C Y
            B Z
            C Z
            C Z
            C Z
            C Z
            C Y
            C Z
            C X
            C Z
            C Z
            C Y
            C Z
            C Z
            C Z
            C Y
            B X
            C Y
            C Z
            C Y
            C Z
            A Y
            C Y
            C Y
            B Y
            C Z
            C Z
            B Z
            A Y
            C Y
            C Y
            A Z
            B Z
            C X
            B Z
            B X
            C Z
            C Y
            C Y
            C Y
            B Z
            C Z
            B Z
            C Z
            C Z
            A X
            C Z
            B X
            C Y
            C X
            C Z
            C Y
            C Z
            C Z
            B Z
            C Z
            C Y
            A X
            C Z
            C Y
            C Z
            B X
            C Y
            C Z
            C Y
            C Y
            C Y
            A Y
            B Z
            C Z
            C Z
            C Z
            C Z
            B Z
            C Z
            C X
            B X
            B Z
            A X
            C Y
            B Y
            C Z
            C Z
            C X
            C Z
            B Z
            C Y
            C Y
            B Y
            C Y
            C Z
            C Z
            C Y
            A Z
            C Y
            B Z
            B Z
            C X
            C X
            C Y
            C Z
            C Z
            C Z
            C Z
            A Y
            C Z
            B Z
            A Y
            C Z
            C Y
            A X
            B Z
            C Z
            C Z
            C Z
            C Z
            B Z
            C Y
            B Z
            C Y
            C Y
            A X
            B Z
            C Y
            B Z
            B Z
            A Z
            A Y
            C Y
            C Y
            C Z
            C Z
            A X
            C Z
            C X
            C Y
            C Z
            C Y
            C Z
            C Z
            C Z
            C Y
            A X
            C Z
            C Y
            C Z
            C Z
            C Y
            C Z
            C Y
            C Y
            A X
            B Z
            C Y
            C Z
            C Z
            C Y
            C Y
            C Z
            C Z
            A Y
            C Y
            B Z
            B Z
            C X
            B Z
            B Z
            C Z
            B Z
            C Z
            C Y
            C Y
            C Y
            A Y
            C Z
            C Z
            C Y
            B X
            C Y
            C Y
            C X
            C Y
            C Z
            B X
            C Z
            B Z
            C Y
            C Z
            C Z
            B Z
            C Z
            C Y
            C X
            B Z
            C Y
            C Z
            C Z
            C Z
            A Y
            C Z
            C Z
            C Y
            C Z
            C Y
            C Y
            C Z
            C Y
            A X
            C Y
            C Z
            C Z
            C Z
            C Y
            C Y
            C Z
            B Z
            C Z
            B Z
            C Z
            C Y
            A Y
            C Z
            C X
            C Y
            C Y
            B Z
            C Z
            C Z
            B Z
            C Y
            C Y
            C Y
            C Z
            C Z
            B Z
            C Z
            B Z
            B Y
            B Z
            A Y
            C Y
            C Y
            C Z
            C Y
            C Z
            C Y
            B Z
            C Z
            C Z
            C Z
            C Z
            B X
            B Z
            C Z
            B Z
            C Y
            A X
            C Y
            B Z
            B Z
            B Z
            C Y
            B Y
            B Z
            C Z
            B Z
            B Z
            C Z
            A Y
            C Z
            C Z
            C Z
            B Z
            C Z
            C Z
            A Y
            B Z
            A Y
            A Y
            C Y
            C Z
            C Z
            C Z
            C Y
            C Z
            C Z
            B Z
            C Y
            C Y
            A X
            C Y
            B Z
            C Y
            B Z
            C Y
            A X
            C Z
            C Z
            C Y
            C Z
            B Z
            C Y
            C Z
            B Z
            C Y
            B Z
            C Z
            C Y
            C Y
            C Y
            C X
            C X
            C Z
            C Z
            A Z
            B X
            C Y
            A Y
            C X
            A Y
            C Y
            B Y
            A X
            A X
            C Y
            C Z
            C Z
            B Z
            B Z
            C Z
            B Z
            B Z
            B Z
            C X
            C Z
            C Z
            B Z
            C Z
            C Y
            C X
            B Z
            C X
            B Z
            C Z
            C Z
            B Z
            C Y
            C Z
            C Y
            B Z
            B Z
            C Y
            A X
            C Y
            C Z
            B Z
            C Z
            C Y
            C Z
            C Y
            C Y
            C Z
            C Y
            C Z
            C Z
            A Y
            C Y
            C Y
            C Y
            A Z
            B Z
            C Z
            C Y
            C Z
            C Y
            B X
            C Z
            A X
            B Y
            C Z
            C Z
            C Z
            C Y
            C Z
            C Z
            C Z
            C Y
            B Y
            C Y
            C Z
            C X
            C Y
            B Z
            A Y
            B Z
            C Y
            C Y
            C Z
            C Z
            A X
            C X
            B Z
            C Z
            B Z
            B Z
            C Z
            C Y
            C Y
            C Y
            B Z
            C Y
            A Y
            C Z
            C Z
            C Z
            C Z
            C Z
            B Z
            C Z
            C Z
            C Z
            A X
            A X
            C Y
            B Y
            C Z
            B Z
            B Z
            A Y
            C Z
            B Z
            C Y
            C Z
            B Z
            C Z
            C Y
            C Z
            C Y
            C Z
            A Y
            C Z
            C Z
            B Y
            A Y
            C Z
            C Y
            B Z
            C X
            A Y
            B Z
            C Z
            B Y
            C X
            C Y
            C Y
            C Z
            C Y
            B Y
            C Z
            B Z
            C Y
            C Y
            C Z
            C Z
            B Z
            A Y
            C X
            C Y
            C X
            B Z
            C Z
            C Z
            C X
            C Y
            B X
            C Y
            C Z
            C Y
            C Y
            C Z
            C Z
            B Z
            C Y
            C Y
            A X
            B Z
            B Z
            B Z
            B Z
            C Y
            C Y
            C Z
            A Y
            B Z
            C Y
            C Y
            C Y
            C Y
            C Y
            C Z
            C Y
            C Z
            C Z
            C Y
            C Y
            C Y
            C Z
            C Z
            C Z
            C Z
            C Z
            A X
            C Y
            B Z
            C Y
            A Y
            C Z
            B Z
            C Y
            A Y
            C Y
            B X
            C Y
            C Z
            B Z
            C Z
            C Z
            B Z
            C Z
            B Z
            C X
            C Y
            B Z
            C Z
            B Z
            A Y
            C Z
            B Z
            C Y
            C Y
            C Y
            C Z
            C Z
            B Z
            C Z
            B Z
            A Y
            C Y
            B Z
            B Z
            C Z
            C Y
            C X
            C Y
            C Z
            C Z
            C X
            A Y
            A Z
            C Z
            A Z
            C Z
            C Z
            C Z
            C Z
            C Y
            C Z
            C Y
            C Y
            C Y
            A X
            C Y
            C Z
            C X
            C X
            C Y
            A Y
            C Y
            C Z
            C X
            C Z
            B Z
            C Y
            A X
            C X
            C Z
            C X
            C Y
            C Z
            B Z
            C Z
            B X
            C Y
            C Z
            A Y
            C X
            B Z
            B Z
            C Z
            C Z
            C Z
            B Z
            C Z
            B Z
            C Z
            B Z
            C X
            A X
            B X
            C Y
            C Z
            C Y
            C Z
            C Z
            B Y
            C X
            B Y
            A X
            A X
            C Y
            C Z
            C Y
            C X
            B Z
            C Z
            C Z
            C Z
            C Z
            C Y
            C Z
            C Y
            C Z
            C Z
            C Z
            C Y
            C Y
            C Z
            B Z
            B X
            A X
            B Z
            C Z
            C Z
            B Z
            B Z
            B Z
            C Y
            C Y
            C Y
            C Y
            C Z
            B Z
            C Y
            C Z
            C Z
            C Y
            B Z
            C Z
            C Z
            C X
            C Z
            C Y
            C Y
            C Z
            C X
            C Z
            C Z
            B Z
            B Z
            C Y
            A X
            C X
            C Y
            C Z
            C X
            C Y
            B Z
            C Z
            B Z
            C Y
            C Y
            C Z
            C Z
            C Z
            C Z
            C Z
            C Z
            C Y
            C Y
            C Z
            A X
            C Z
            C Z
            C Z
            C Z
            C X
            C X
            C Z
            B X
            C Z
            C Z
            C Z
            C Z
            C Z
            A X
            C Z
            C Y
            C Y
            B Z
            B Y
            C Z
            C Z
            A X
            C Y
            B X
            B Z
            C Z
            C Y
            C Z
            B Z
            C Z
            C Z
            C Y
            C Z
            C Z
            C Z
            C Z
            C Z
            B Z
            C Y
            C Z
            B Z
            C Y
            C Y
            C X
            C Y
            A X
            C Z
            C Y
            C Y
            C Z
            C X
            C Z
            B Z
            B Z
            A Y
            B Z
            C X
            C Y
            C Z
            C Y
            B X
            B X
            C Y
            C Z
            C Z
            A X
            C Z
            C Y
            C Z
            C Z
            B Z
            B Z
            C Z
            C Z
            C Z
            C Z
            A X
            C Y
            A Z
            C Y
            C Z
            B Z
            C Y
            C X
            C X
            A X
            C Z
            C Y
            C Z
            C Z
            C Y
            B Z
            C Y
            C Y
            C Z
            C X
            B Z
            C Y
            C Y
            C Y
            C Z
            B Z
            B Z
            B Z
            B Z
            C Z
            B Z
            B Z
            B Z
            C Y
            B Z
            B Z
            A Y
            C Z
            C Z
            C Y
            B Z
            C Y
            C Y
            C Y
            C Y
            A X
            C Z
            A Y
            C Y
            C Y
            C Y
            C Z
            B X
            C Z
            B Z
            C X
            C Y
            B Z
            C Y
            C Z
            C Z
            C X
            B Z
            B Z
            C Y
            B Z
            C Y
            C Z
            C Z
            C Y
            A Y
            C Y
            A Z
            B Z
            C Z
            B Y
            C Y
            C Y
            B Z
            C Y
            C X
            C Y
            A Y
            B Z
            C Y
            A Y
            C Y
            C Y
            B Z
            C Z
            C Y
            C Z
            C Y
            C Z
            C Z
            A X
            A X
            C Y
            B Z
            C Y
            C Z
            C X
            A X
            C X
            C Z
            C Z
            B Y
            C Z
            B Z
            C Y
            A X
            C Z
            B Z
            C Z
            C Z
            C Z
            C Y
            C Y
            C Z
            B Z
            C X
            B Y
            B Z
            B Z
            C Y
            B Z
            C Z
            C X
            C Y
            C Y
            C Z
            C Y
            C Y
            B X
            B Z
            B Z
            B Z
            B Z
            C Z
            B X
            C Z
            C Z
            A Z
            C Z
            A Y
            C Z
            C Y
            C Y
            B Z
            C X
            C Y
            C Y
            B Y
            C Y
            B Z
            C Y
            C Y
            A X
            B Z
            C Z
            A X
            C Y
            C Z
            C Z
            A Y
            C Z
            C X
            C Z
            C Y
            C Z
            C Y
            C Y
            C Z
            B Z
            A Y
            C Z
            B Z
            C Z
            C Z
            A Z
            C Z
            C Y
            C Z
            C Z
            C Z
            B Z
            A Y
            C Y
            C Y
            C Y
            C Z
            B Y
            B Z
            C Y
            C Z
            C Z
            C Y
            C Y
            A Z
            B Z
            C X
            B Z
            C Z
            C Y
            A Y
            B Z
            C Y
            C Y
            B Z
            C Z
            C Z
            C Z
            B Z
            C Z
            C Z
            C Z
            C Z
            C Z
            A X
            A X
            B Z
            C Z
            C Z
            C Z
            B Z
            C Z
            B X
            C Y
            C X
            C X
            C Y
            C Z
            C Z
            A X
            A X
            C Z
            C Z
            C Z
            C Z
            C Z
            C Y
            A X
            C X
            C Y
            C Y
            C Y
            A X
            C Y
            B Z
            C Z
            C Z
            A Y
            C Y
            C Z
            C Z
            B Z
            C Y
            C Y
            C Y
            C Z
            B Z
            C Y
            B Z
            C X
            C Y
            A Y
            C Y
            B Z
            B Z
            C Z
            C Z
            A X
            B Z
            C Z
            C Z
            C Z
            C X
            C Y
            C Y
            C Z
            C Y
            C Y
            B Y
            C Z
            B Z
            A Z
            C Z
            C Y
            C Y
            B Y
            C Z
            B Z
            A Y
            C Y
            A Y
            C Y
            C Y
            C Z
            C Z
            C Y
            C Y
            C Z
            C Y
            C Z
            C Y
            C Y
            C Z
            C Y
            C Z
            C X
            C Z
            C Z
            C Y
            B Z
            C X
            B Z
            B Z
            C X
            B X
            C Z
            C Y
            B Z
            C Z
            C Y
            C Z
            C X
            C Z
            C Z
            C Z
            A Y
            C Z
            C Y
            C X
            C Y
            C Z
            C Z
            C Y
            B Z
            C Z
            B X
            C Y
            C Y
            C X
            C Z
            C Z
            C Y
            C Z
            B Z
            C Z
            C X
            B Z
            C Y
            C Z
            B Z
            C Y
            B X
            C Z
            C Z
            C Z
            C Y
            C Z
            C Y
            A Y
            C Y
            C Y
            C Z
            C Z
            B Z
            B Z
            C Y
            C X
            C Z
            C Z
            C Z
            C Z
            A X
            C Y
            C Y
            C X
            C Z
            A X
            A Y
            C Y
            A Y
            C Y
            C Y
            C Z
            C Z
            C Y
            B Z
            C Y
            B Z
            C Y
            C Y
            A X
            C Y
            C Z
            B Z
            A Y
            A Y
            C X
            B Z
            B Z
            C Z
            C X
            C X
            C Y
            C Y
            C X
            A X
            C Z
            C Y
            B Z
            C Z
            C Z
            A Y
            C X
            C X
            C Z
            C Y
            A Y
            C Z
            C Z
            B Z
            C Z
            C X
            C Z
            A Y
            C Y
            C Y
            C Y
            B X
            C Z
            C Y
            B Y
            C Y
            C Z
            C Z
            A Z
            C Z
            A Y
            B Z
            C Y
            B Z
            C Y
            C Y
            C Z
            C X
            A Y
            C Z
            A Z
            C Y
            C Z
            C Y
            C Y
            C Z
            B Z
            A Y
            C Y
            A Y
            B Z
            C Z
            C Z
            C Z
            C Z
            C Z
            C Z
            C Z
            C Y
            B Z
            B Z
            C Y
            C Z
            A Y
            C Z
            C Z
            C Z
            C X
            C Z
            A X
            B Z
            C Z
            C Z
            B Z
            B Y
            C Z
            C Z
            C Z
            C Z
            C Z
            C Z
            B Z
            C Z
            A X
            C Y
            C Z
            B Z
            B Z
            B Z
            B Z
            C Z
            B Z
            C Y
            A X
            B Z
            C Z
            B Z
            B Z
            C Y
            B Z
            C Y
            C Z
            A Y
            C Y
            C X
            C Y
            C Y
            B Z
            C Y
            C Z
            C Y
            C Z
            B Z
            C Z
            B Z
            A Y
            C Z
            C Y
            C Y
            B Z
            C Z
            C Y
            C Y
            C Z
            A Y
            C Z
            C Y
            C Z
            B Z
            C Z
            C Z
            C Z
            C Y
            C Z
            C Z
            B Z
            C Z
            C Z
            C Z
            B Z
            C Z
            C Z
            C Y
            C Y
            A X
            C Z
            C Z
            B Z
            C Z
            C Z
            C X
            C Z
            C X
            A X
            B Z
            A X
            C Z
            C X
            C Y
            C Z
            B X
            C Y
            C X
            B X
            C Y
            B X
            C Y
            C Z
            B Z
            C Y
            C Y
            C Z
            C Z
            B Z
            C Z
            C Y
            C Z
            B Z
            C Z
            A Y
            B X
            C Y
            C Z
            A X
            C Y
            A X
            C Z
            C Z
            C Z
            B X
            B Z
            B Z
            B Z
            B Z
            C Z
            B Z
            A Z
            C X
            B Z
            C Z
            C Z
            C Z
            B Z
            B X
            C Z
            C Y
            C Y
            C X
            C Z
            C Y
            C Z
            B Z
            B Z
            A Y
            A Y
            C Z
            B Y
            C Z
            B Z
            C Y
            B Z
            C Z
            B Z
            C Z
            A Y
            C Z
            C X
            C Z
            C Y
            C Y
            C Z
            B Z
            C Y
            C Z
            C Z
            C Z
            A Y
            C Z
            C Z
            C Y
            C Z
            A Y
            A Z
            B X
            C Y
            C Z
            C Z
            C Z
            C Z
            B Z
            C Y
            A X
            C Z
            A Y
            C Z
            C Z
            C Z
            C Y
            B Y
            B X
            B Z
            C Z
            A X
            A Y
            C Z
            C Y
            C Z
            B X
            B Y
            C Y
            C Y
            C Z
            C Z
            C Z
            B Y
            C Z
            C Y
            C Z
            C Y
            C Y
            C Y
            B Z
            B Z
            A Y
            C Y
            A X
            C Z
            C Z
            B Z
            A Y
            B Z
            C X
            C Y
            B X
            C Z
            A X
            C Z
            C Y
            C Y
            C Y
            C Z
            C Z
            C Y
            A Y
            C Z
            C Z
            C X
            C Z
            C Y
            C Z
            C Z
            A Y
            A Y
            B Z
            C Y
            B Z
            C Z
            C X
            C Z
            B Z
            A Y
            C Z
            B Z
            C Y
            C Z
            C X
            C Y
            A X
            C Z
            B Z
            C Y
            B Y
            C Z
            B Y
            A Y
            C X
            C Z
            A Y
            B Z
            A X
            C Y
            C Z
            C Z
            C Y
            C Y
            B X
            A Y
            C Z
            C Y
            C Z
            C Z
            B Z
            C Z
            B Z
            C X
            C Y
            A Y
            C Z
            C Y
            C Z
            C Z
            C Y
            C Z
            C Y
            C Y
            B Z
            C Z
            C Z
            C Z
            B Z
            C Y
            C Z
            C Z
            C Z
            A X
            C Y
            C Y
            A X
            A X
            C X
            C Z
            B Z
            C Z
            C Y
            C X
            C Z
            B X
            C X
            A X
            C X
            C Y
            A Y
            C Y
            C Z
            C Z
            C Y
            C Z
            A X
            B Z
            C Z
            C Y
            C Z
            C Y
            C Y
            C Y
            C Z
            C Y
            B X
            C Z
            C Y
            C Y
            C Y
            B Y
            C Z
            C Z
            C Z
            C Y
            B Z
            C Y
            A X
            B Z
            C Y
            C Y
            C Z
            B Z
            B Z
            C Z
            B Z
            B Z
            A Y
            C Z
            C Z
            C Z
            C Y
            C Z
            C Z
            C X
            B Z
            C Y
            B Z
            B Z
            B Y
            A Y
            C Z
            C X
            C Z
            C Z
            C Z
            C Y
            C Z
            C Z
            C X
            A X
            B X
            A Y
            A X
            C Y
            C Y
            C Y
            B X
            A Y
            C Z
            C Y
            A Y
            C Z
            C Y
            C Y
            C Z
            C Z
            B X
            C X
            C Z
            C Z
            B Z
            C Y
            C Z
            C Z
            C Y
            C Z
            C Z
            B Z
            C Y
            C Z
            B Z
            C Y
            C Y
            C Z
            C Y
            C X
            C Z
            C Y
            A Y
            C Z
            B Z
            C X
            C Y
            B Z
            B Z
            C Z
            C Z
            C Y
            C Y
            C Z
            B X
            A X
            C Z
            C Z
            A Y
            C Y
            C Z
            B Z
            C Y
            A X
            C Y
            C Z
            C Z
            C Y
            C Z
            C Z
            C Z
            B Z
            B Z
            C X
            C Y
            C Z
            C Z
            C Z
            C Z
            A X
            C Y
            C Y
            C Z
            B Z
            C Y
            C Y
            A X
            C X
            B Z
            C Y
            C Y
            B X
            C Y
            C Z
            C Z
            C Y
            C Y
            C Z
            C Y
            C Z
            C Z
            C Y
            C Z
            C Z
            B Z
            C Z
            C Z
            C Z
            C Y
            C Y
            C Z
            C Y
            C Z
            B X
            A X
            C Y""";
}
